import React from 'react';
import { Head, useForm } from '@inertiajs/react';
import SuperAdminNav from '@/Components/SuperAdminNav';

export default function PaymentSettings({ activeSetting, history = [], requests = [] }) {
  const initial = useForm({ bank_name: '', account_name: '', account_number: '' });
  const review = useForm({ action: 'approve', review_note: '' });
  return <div className="min-h-screen bg-[#F7F3ED] text-[#2C1E16]"><Head title="Super Admin Payment Settings" /><SuperAdminNav active="payments" /><main className="p-6 md:p-10"><div className="mx-auto max-w-5xl space-y-6"><div className="border-b border-[#2C1E16]/10 pb-6"><p className="text-[11px] font-bold uppercase tracking-[.2em] text-violet-700">Financial governance</p><h1 className="mt-2 text-3xl font-bold">Company Payment Account</h1></div><section className="border border-[#2C1E16]/10 bg-white p-6"><h2 className="text-xl font-bold">Rekening aktif</h2>{activeSetting ? <p className="mt-3">{activeSetting.bank_name} · {activeSetting.account_name} · <b>{activeSetting.account_number}</b></p> : <form onSubmit={e => { e.preventDefault(); initial.post(route('super-admin.payment-settings.store')); }} className="mt-4 grid gap-3"><input value={initial.data.bank_name} onChange={e => initial.setData('bank_name', e.target.value)} placeholder="Bank Name" className="rounded-xl border p-3" /><input value={initial.data.account_name} onChange={e => initial.setData('account_name', e.target.value)} placeholder="Account Name" className="rounded-xl border p-3" /><input value={initial.data.account_number} onChange={e => initial.setData('account_number', e.target.value)} placeholder="Account / VA Number" className="rounded-xl border p-3" /><button className="rounded-xl bg-violet-800 text-white p-3 font-bold">Aktifkan Payment Account</button></form>}</section><section className="border border-[#2C1E16]/10 bg-white p-6"><h2 className="font-bold text-xl">Review Request</h2>{requests.filter(r => r.status === 'pending').map(request => <form key={request.id} onSubmit={e => { e.preventDefault(); review.post(route('super-admin.payment-settings.requests.review', request.id)); }} className="mt-4 border-t pt-4"><p>{request.proposed_bank_name} · {request.proposed_account_name} · {request.proposed_account_number}</p><p className="text-sm text-[#2C1E16]/60">{request.reason}</p><textarea value={review.data.review_note} onChange={e => review.setData('review_note', e.target.value)} placeholder="Catatan review (wajib untuk reject)" className="mt-3 w-full rounded-xl border p-3" /><div className="mt-3 flex gap-2"><button type="button" onClick={() => { review.setData('action', 'reject'); review.post(route('super-admin.payment-settings.requests.review', request.id)); }} className="rounded-xl border px-4 py-2">Reject</button><button className="rounded-xl bg-violet-800 text-white px-4 py-2">Approve</button></div></form>)}</section><section className="border border-[#2C1E16]/10 bg-white p-6"><h2 className="font-bold">Riwayat Setting</h2>{history.map(setting => <p key={setting.id} className="mt-2 text-sm">{setting.is_active ? 'Aktif' : 'Riwayat'} — {setting.bank_name} / {setting.account_number}</p>)}</section></div></main></div>;
}
