import { Head, Link, useForm, usePage } from '@inertiajs/react';
import { ArrowLeft, ShoppingBag, MapPin, Truck, Zap, X, CheckCircle2 } from 'lucide-react';
import { AnimatePresence, motion } from 'framer-motion';
import { useState } from 'react';
import { cloneElement } from 'react';

const rupiah = (amount) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(amount);

export default function Checkout({ items, auth }) {
    const { flash } = usePage().props;
    const [confirming, setConfirming] = useState(false);
    const { data, setData, post, processing, errors } = useForm({
        cart_item_ids: items.map((item) => item.id), shipping_method: 'regular', payment_method: 'virtual_account',
        customer_name: auth.user.name ?? '', customer_phone: auth.user.phone ?? '', customer_address: auth.user.address ?? '', customer_note: '',
    });
    const subtotal = items.reduce((total, item) => total + Number(item.product.price) * item.qty, 0);
    const deliveryFee = data.shipping_method === 'instant' ? 30000 : 25000;
    const total = subtotal + deliveryFee;

    return <div className="min-h-screen bg-[#FDFBF7] text-[#2C1E16]">
        <Head title="Checkout" />
        <header className="border-b border-[#2C1E16]/10 bg-white"><div className="mx-auto flex h-20 max-w-6xl items-center justify-between px-6"><Link href={route('home')} className="flex h-10 w-10 items-center justify-center overflow-hidden rounded-full border border-[#2C1E16]/20 bg-white transition-colors hover:border-[#D4813E]"><img src="/images/logo.png" alt="Beranda Kopi Gajahmada" className="h-full w-full object-cover" /></Link><Link href={route('cart.index')} className="inline-flex min-h-10 items-center gap-2 rounded-full border border-[#2C1E16]/12 bg-[#FDFBF7] px-4 text-sm font-semibold transition-colors hover:border-[#D4813E]/45 hover:bg-[#FFF5EA] hover:text-[#D4813E]"><ArrowLeft size={16} /> Kembali ke Keranjang</Link></div></header>
        <main className="mx-auto max-w-6xl px-6 py-10">
            {flash?.success && <div className="mb-6 rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4 text-emerald-800">{flash.success}</div>}
            <div className="mb-8 flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#FFE9D2] text-[#D4813E]"><ShoppingBag size={22} /></div><div><h1 className="text-3xl font-bold">Checkout</h1><p className="text-sm text-[#2C1E16]/60">Konfirmasi produk dan data pengiriman Anda.</p></div></div>
            <form onSubmit={(event) => { event.preventDefault(); setConfirming(true); }} className="grid gap-8 lg:grid-cols-[1.45fr_0.85fr]">
                <div className="space-y-6">
                    <section className="rounded-3xl border border-[#2C1E16]/10 bg-white p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-bold">Produk yang dipilih</h2><p className="mt-1 text-sm text-[#2C1E16]/60">Ubah produk atau jumlahnya dari Keranjang Saya.</p></div><Link href={route('cart.index')} className="shrink-0 text-sm font-bold text-[#D4813E] hover:underline">Ubah keranjang</Link></div><div className="mt-5 divide-y divide-[#2C1E16]/10">{items.map((item) => <div key={item.id} className="flex gap-4 py-4 first:pt-0 last:pb-0"><img src={item.product.image ? `/storage/${item.product.image}` : '/images/placeholder-coffee.png'} alt={item.product.product_name} className="h-16 w-16 rounded-2xl object-cover" /><div className="min-w-0 flex-1"><p className="font-bold">{item.product.product_name}</p><p className="text-sm text-[#2C1E16]/60">{item.brew_method === 'espresso' ? 'Espresso' : 'Filter'} · {item.qty} pcs</p></div><p className="text-sm font-bold">{rupiah(Number(item.product.price) * item.qty)}</p></div>)}</div>{errors.cart_item_ids && <p className="mt-4 text-sm text-red-600">{errors.cart_item_ids}</p>}<div className="mt-6 flex justify-center sm:justify-start"><Link href={`${route('home')}#shop`} className="inline-flex min-h-11 items-center justify-center rounded-full border border-[#D4813E]/40 bg-[#FFF5EA] px-5 py-2.5 text-sm font-bold text-[#D4813E] transition hover:bg-[#D4813E] hover:text-white sm:px-4">Tambah produk lain</Link></div></section>
                    <section className="overflow-hidden rounded-[2rem] bg-[#FFF5EA] p-1"><div className="rounded-[1.8rem] bg-white px-6 py-7 md:px-8"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#2C1E16] text-[#FDFBF7]"><MapPin size={19}/></span><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#D4813E]">Langkah 1 dari 2</p><h2 className="text-lg font-bold">Informasi pengiriman</h2></div></div><p className="mt-5 border-b border-[#2C1E16]/10 pb-5 text-sm leading-relaxed text-[#2C1E16]/60">Kami gunakan data ini untuk memastikan pesanan tiba ke penerima yang tepat.</p><div className="mt-2 grid gap-x-8 sm:grid-cols-2"><Field label="Nama penerima" error={errors.customer_name}><input value={data.customer_name} onChange={(e) => setData('customer_name', e.target.value)} placeholder="Nama lengkap penerima" /></Field><Field label="Nomor WhatsApp" error={errors.customer_phone}><input type="tel" value={data.customer_phone} onChange={(e) => setData('customer_phone', e.target.value)} placeholder="Contoh: 0812 3456 7890" /></Field><Field label="Alamat lengkap" error={errors.customer_address} className="sm:col-span-2"><textarea rows="3" value={data.customer_address} onChange={(e) => setData('customer_address', e.target.value)} placeholder="Nama jalan, nomor rumah, kelurahan, kecamatan, dan kota" /></Field><Field label="Catatan untuk pesanan" hint="Opsional" error={errors.customer_note} className="sm:col-span-2"><textarea rows="2" value={data.customer_note} onChange={(e) => setData('customer_note', e.target.value)} placeholder="Contoh: Titip di satpam atau hubungi sebelum mengantar" /></Field></div></div></section>
                    <section className="rounded-3xl border border-[#2C1E16]/10 bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Metode pengiriman</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{[['regular', 'Regular', 25000, Truck, 'Estimasi 2–4 hari kerja. Pilihan hemat untuk pengiriman antarkota.'], ['instant', 'Instant', 30000, Zap, 'Prioritas diproses dan dikirim lebih cepat di area layanan yang tersedia.']].map(([value, label, price, Icon, description]) => <label key={value} className={`cursor-pointer rounded-2xl border p-4 transition-all ${data.shipping_method === value ? 'border-[#D4813E] bg-[#FFE9D2]/40 shadow-sm' : 'border-[#2C1E16]/10 hover:border-[#D4813E]/50'}`}><input type="radio" className="sr-only" value={value} checked={data.shipping_method === value} onChange={(e) => setData('shipping_method', e.target.value)} /><span className="flex items-center gap-2 font-bold"><Icon size={17} className="text-[#D4813E]"/>{label}</span><span className="mt-1 block text-sm text-[#2C1E16]/60">{rupiah(price)}</span>{data.shipping_method === value && <motion.p initial={{opacity:0,height:0}} animate={{opacity:1,height:'auto'}} className="mt-3 border-t border-[#D4813E]/20 pt-3 text-xs leading-relaxed text-[#2C1E16]/65">{description}</motion.p>}</label>)}</div>{errors.shipping_method && <p className="mt-3 text-sm text-red-600">{errors.shipping_method}</p>}</section>
                </div>
                <aside className="h-fit rounded-3xl bg-[#2C1E16] p-6 text-white lg:sticky lg:top-6"><h2 className="text-xl font-bold">Ringkasan pesanan</h2><div className="mt-6 space-y-3 border-b border-white/15 pb-5 text-sm"><div className="flex justify-between"><span className="text-white/70">Subtotal</span><span>{rupiah(subtotal)}</span></div><div className="flex justify-between"><span className="text-white/70">Pengiriman</span><span>{rupiah(deliveryFee)}</span></div></div><div className="mt-5 flex justify-between text-lg font-bold"><span>Total</span><span>{rupiah(total)}</span></div><p className="mt-5 text-sm leading-relaxed text-white/70">Setelah pesanan dibuat, selesaikan pembayaran melalui Virtual Account dan unggah bukti pembayaran.</p><button type="submit" disabled={processing} className="mt-6 w-full rounded-full bg-[#D4813E] px-5 py-3 font-bold hover:bg-[#b86b30] disabled:opacity-60">{processing ? 'Memproses...' : 'Buat Pesanan'}</button></aside>
            </form>
            <AnimatePresence>{confirming && <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[60] grid place-items-center bg-[#2C1E16]/45 p-4"><motion.div initial={{scale:.94,y:16}} animate={{scale:1,y:0}} exit={{scale:.94,y:16}} className="w-full max-w-md rounded-[2rem] bg-white p-7 shadow-2xl"><button onClick={() => setConfirming(false)} className="float-right rounded-full p-2 hover:bg-orange-50"><X size={18}/></button><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#FFE9D2] text-[#D4813E]"><CheckCircle2/></span><h2 className="mt-5 text-2xl font-bold">Pesanan sudah sesuai?</h2><p className="mt-2 text-sm leading-relaxed text-[#2C1E16]/65">Periksa kembali produk, alamat, dan metode pengiriman. Setelah dibuat, pesanan akan menunggu pembayaran.</p><div className="mt-7 grid grid-cols-2 gap-3"><button type="button" onClick={() => setConfirming(false)} className="rounded-full border border-[#2C1E16]/15 px-4 py-3 font-bold hover:bg-[#FDFBF7]">Belum, cek lagi</button><button type="button" onClick={() => { setConfirming(false); post(route('orders.store')); }} disabled={processing} className="rounded-full bg-[#D4813E] px-4 py-3 font-bold text-white hover:bg-[#b86b30] disabled:opacity-60">Ya, buat pesanan</button></div></motion.div></motion.div>}</AnimatePresence>
        </main>
    </div>;
}

function Field({ label, hint, error, className = '', children }) {
    const controlClass = `mt-2 w-full border-0 border-b border-[#2C1E16]/15 bg-transparent px-0 py-3 text-sm text-[#2C1E16] outline-none transition placeholder:text-[#2C1E16]/35 focus:border-[#D4813E] focus:ring-0 ${children.type === 'textarea' ? 'resize-none' : ''}`;
    return <label className={`group block px-0 py-5 ${className}`}><span className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.12em] text-[#2C1E16]/60">{label}{hint && <em className="normal-case tracking-normal text-[#2C1E16]/35">{hint}</em>}</span>{cloneElement(children, { className: controlClass })}{error && <span className="mt-2 block text-xs text-red-600">{error}</span>}</label>;
}
