import React from 'react';
import { Head, Link, useForm } from '@inertiajs/react';

const labels = { submitted: 'Baru masuk', in_review: 'Sedang ditinjau', resolved: 'Selesai', rejected: 'Ditolak' };

export default function ComplaintShow({ complaint, canManage }) {
  const reply = useForm({ message: '' });
  const closed = ['resolved', 'rejected'].includes(complaint.status);
  return <div className="min-h-screen bg-[#FDFBF7] px-6 py-10 text-[#2C1E16]"><Head title="Detail Komplain" /><main className="mx-auto max-w-3xl"><Link href={canManage ? route('admin.complaints.index') : route('orders.show', complaint.order_id)} className="text-sm font-bold text-[#D4813E]">← Kembali</Link><section className="mt-5 rounded-[2rem] border bg-white p-7 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-[#2C1E16]/50">Komplain {complaint.order?.order_number}</p><h1 className="mt-2 text-2xl font-bold">{complaint.item?.product_name || 'Masalah Pengiriman'}</h1><p className="mt-2 text-sm text-[#2C1E16]/70">{complaint.description}</p></div><span className="rounded-full bg-[#D4813E]/10 px-3 py-2 text-xs font-bold text-[#D4813E]">{labels[complaint.status]}</span></div>{complaint.admin_note && <div className="mt-5 rounded-xl bg-amber-50 p-4 text-sm"><b>Catatan admin:</b> {complaint.admin_note}</div>}{complaint.evidences?.length > 0 && <div className="mt-6"><h2 className="text-sm font-bold">Foto bukti</h2><div className="mt-3 grid grid-cols-2 gap-3">{complaint.evidences.map((evidence) => <a key={evidence.id} href={route('complaints.evidence', [complaint.id, evidence.id])} target="_blank" rel="noreferrer"><img src={route('complaints.evidence', [complaint.id, evidence.id])} alt={evidence.original_name} className="h-40 w-full rounded-xl border object-cover" /></a>)}</div></div>}<div className="mt-7 border-t pt-5"><h2 className="font-bold">Percakapan</h2><div className="mt-4 space-y-3">{complaint.messages?.length ? complaint.messages.map((message) => <div key={message.id} className={`rounded-2xl p-4 text-sm ${message.user?.role === 'admin' || message.user?.role === 'super_admin' ? 'bg-[#2C1E16] text-white' : 'bg-[#FDFBF7]'}`}><p className="text-xs font-bold opacity-70">{message.user?.name} · {new Date(message.created_at).toLocaleString('id-ID')}</p><p className="mt-2 whitespace-pre-line">{message.message}</p></div>) : <p className="text-sm text-[#2C1E16]/60">Belum ada balasan.</p>}</div>{!closed && <form onSubmit={(event) => { event.preventDefault(); reply.post(route('complaints.replies.store', complaint.id), { onSuccess: () => reply.reset() }); }} className="mt-5"><textarea value={reply.data.message} onChange={(event) => reply.setData('message', event.target.value)} required maxLength="3000" placeholder="Tulis balasan" className="min-h-24 w-full rounded-xl border p-3 text-sm" />{reply.errors.message && <p className="text-xs text-red-600">{reply.errors.message}</p>}<button disabled={reply.processing} className="mt-3 rounded-xl bg-[#D4813E] px-4 py-2 text-sm font-bold text-white">Kirim balasan</button></form>}</div></section></main></div>;
}
