import React from 'react';
import { Head, Link, router, useForm } from '@inertiajs/react';
import AdminBackButton from '@/Components/AdminBackButton';
import AdminPanelNav from '@/Components/AdminPanelNav';

const labels = { submitted: 'Baru masuk', in_review: 'Sedang ditinjau', resolved: 'Selesai', rejected: 'Ditolak' };

export default function ComplaintIndex({ complaints, filters = {} }) {
  const rows = complaints.data || [];
  const status = useForm({ status: 'in_review', admin_note: '' });
  const update = (complaint) => { const adminNote = window.prompt('Catatan keputusan untuk pelanggan (opsional)', complaint.admin_note || ''); router.patch(route('admin.complaints.update', complaint.id), { status: status.data.status, admin_note: adminNote ?? complaint.admin_note ?? '' }, { preserveScroll: true }); };
  return <><AdminPanelNav active="complaints"/><main className="min-h-screen bg-[#FDFBF7] p-4 text-[#2C1E16] sm:p-6 md:p-10"><Head title="Kelola Komplain"/><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-[#D4813E]">Admin</p><h1 className="mt-2 text-3xl font-bold">Kelola Komplain</h1></div><AdminBackButton href={route('admin.dashboard')} label="Kembali ke Ringkasan"/></div><form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); router.get(route('admin.complaints.index'), Object.fromEntries(form)); }} className="mt-6 flex flex-wrap gap-3 rounded-2xl border bg-white p-4"><input name="search" defaultValue={filters.search || ''} placeholder="Pesanan, pelanggan, isi komplain" className="min-w-0 flex-1 rounded-xl border p-2.5 text-sm"/><select name="status" defaultValue={filters.status || ''} className="rounded-xl border p-2.5 text-sm"><option value="">Semua status</option>{Object.entries(labels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><button className="rounded-xl bg-[#2C1E16] px-4 text-sm font-bold text-white">Filter</button></form><section className="mt-5 overflow-hidden rounded-2xl border bg-white"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-[#FDFBF7]"><tr><th className="p-4">Pesanan / Pelanggan</th><th className="p-4">Topik</th><th className="p-4">Status</th><th className="p-4">Aksi</th></tr></thead><tbody>{rows.map((complaint) => <tr key={complaint.id} className="border-t align-top"><td className="p-4"><b>{complaint.order?.order_number}</b><br/><span className="text-xs text-[#2C1E16]/60">{complaint.customer?.name}</span></td><td className="p-4">{complaint.item?.product_name || 'Pengiriman'}<br/><span className="text-xs text-[#2C1E16]/60">{complaint.description.slice(0, 90)}</span></td><td className="p-4"><span className="font-bold text-[#D4813E]">{labels[complaint.status]}</span></td><td className="p-4"><Link href={route('complaints.show', complaint.id)} className="text-xs font-bold text-[#D4813E]">Buka percakapan</Link><div className="mt-3 flex gap-2"><select value={status.data.status} onChange={(event) => status.setData('status', event.target.value)} className="rounded border p-1 text-xs">{Object.entries(labels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><button onClick={() => update(complaint)} disabled={status.processing} className="rounded bg-[#2C1E16] px-2 text-xs font-bold text-white">Simpan</button></div></td></tr>)}{rows.length === 0 && <tr><td colSpan="4" className="p-8 text-center text-[#2C1E16]/60">Belum ada komplain.</td></tr>}</tbody></table></div></section></div></main></>;
}
