import { Link, usePage } from '@inertiajs/react';
import { LayoutDashboard, LogOut, Menu, UserRound, X } from 'lucide-react';
import { useState } from 'react';

export default function ProfileLayout({ header, children }) {
    const user = usePage().props.auth.user;
    const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

    return <div className="min-h-screen bg-[#FDFBF7] text-[#2C1E16]">
        <nav className="border-b border-[#2C1E16]/10 bg-[#FDFBF7]/90 backdrop-blur-md"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-6"><Link href={route('home')} className="flex h-10 w-10 items-center justify-center overflow-hidden rounded-full border border-[#2C1E16]/15 bg-white transition-colors hover:border-[#D4813E]"><img src="/images/logo.png" alt="Beranda Kopi Gajahmada" className="h-full w-full object-cover" /></Link><div className="hidden items-center gap-3 sm:flex"><Link href={route('dashboard')} className="inline-flex min-h-10 items-center gap-2 rounded-full px-4 text-sm font-semibold text-[#2C1E16]/70 transition hover:bg-[#FFE9D2] hover:text-[#D4813E]"><LayoutDashboard size={17} /> Dashboard</Link><span className="h-7 w-px bg-[#2C1E16]/10" /><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#FFE9D2] text-[#D4813E]"><UserRound size={18} /></span><span className="max-w-36 truncate text-sm font-semibold">{user.name}</span><Link href={route('logout')} method="post" as="button" className="inline-flex min-h-10 items-center gap-2 rounded-full border border-[#2C1E16]/12 bg-white px-4 text-sm font-semibold transition hover:border-red-200 hover:bg-red-50 hover:text-red-600"><LogOut size={16} /> Keluar</Link></div><button type="button" onClick={() => setIsMobileMenuOpen((open) => !open)} className="rounded-full p-2 text-[#2C1E16] transition hover:bg-[#FFE9D2] sm:hidden" aria-expanded={isMobileMenuOpen} aria-label="Buka navigasi akun">{isMobileMenuOpen ? <X size={21} /> : <Menu size={21} />}</button></div>{isMobileMenuOpen && <div className="border-t border-[#2C1E16]/10 bg-white px-5 py-4 sm:hidden"><div className="flex items-center gap-3 border-b border-[#2C1E16]/10 pb-4"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#FFE9D2] text-[#D4813E]"><UserRound size={19} /></span><div className="min-w-0"><p className="truncate text-sm font-bold">{user.name}</p><p className="truncate text-xs text-[#2C1E16]/55">{user.email}</p></div></div><div className="mt-3 grid gap-2"><Link href={route('dashboard')} onClick={() => setIsMobileMenuOpen(false)} className="flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm font-semibold hover:bg-[#FFF5EA]"><LayoutDashboard size={17} /> Dashboard</Link><Link href={route('logout')} method="post" as="button" className="flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm font-semibold text-red-600 hover:bg-red-50"><LogOut size={17} /> Keluar</Link></div></div>}</nav>
        {header && <header className="border-b border-[#2C1E16]/10 bg-white/70"><div className="mx-auto max-w-7xl px-5 py-5 sm:px-6">{header}</div></header>}
        <main>{children}</main>
    </div>;
}
